# Generated by Django 4.0.4 on 2022-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=40, verbose_name='eng')),
                ('ru', models.CharField(max_length=40, verbose_name='ru')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('dateTime', models.DateTimeField(auto_now=True, verbose_name='dateTime')),
            ],
        ),
    ]
